import { redactSensitiveText } from '../runtime/NoeContextScrubber.js';

export const NOE_FREEDOM_MANIFEST_SCHEMA_VERSION = 1;

export const NOE_FREEDOM_AUTH_MODES = new Set([
  'dry_run',
  'owner_supervised_unrestricted',
  'developer_unrestricted',
]);

export const NOE_FREEDOM_DEVELOPER_MODE_PROFILE = {
  id: 'developer_unrestricted',
  label: '开发者最大权限',
  mode: 'developer_unrestricted',
  description: 'Owner-present developer mode for full local computer and account automation through Noe Freedom tools.',
  skipsTrustManifestAndAllowlist: true,
  ownerPresenceRequired: true,
  stillRedactsSecretValues: true,
  canUseLoggedInAccounts: true,
  canControlAllOwnerAuthorizedAccounts: true,
  canUseBrowserLoggedInSessions: true,
  canUseSecretRefs: true,
  canUseKeychainSecretRefs: true,
  canUseEnvSecretRefs: true,
  canUseSshAgentAndConfiguredKeys: true,
  canRunLocalShell: true,
  canRunSsh: true,
  canRunMacAutomation: true,
  canOpenBrowserAccounts: true,
  canPublishExternally: true,
  canUploadFiles: true,
  canDeleteFiles: true,
  canDeleteOrHideExternally: true,
  canRollbackPublishedContent: true,
  canUseToolMarketplace: true,
  allowedCapabilityPrefixes: [
    'shell.',
    'ssh.',
    'secret.',
    'desktop.',
    'file.',
    'account.',
    'browser.',
    'automation.',
    'social.',
    'network.',
    'tool.',
    'workflow.',
  ],
  hardVetoes: [
    'system_root_delete',
    'codex_runtime_delete',
    'secret_plaintext_output',
  ],
};

export const BUILTIN_FREEDOM_TOOLS = [
  {
    id: 'noe.freedom.shell.execute',
    name: '自由 Shell 执行',
    description: '在 owner-supervised unrestricted 模式下执行本机 shell 命令；支持 dry-run、证据和回滚提示。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.shell.execute',
    capability: 'shell.exec',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['unrestricted', 'shell', 'exec', 'terminal', '自由执行'],
    rollback: { strategy: 'caller_defined', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.ssh.execute',
    name: '本地 SSH 执行',
    description: '通过本机 SSH 配置执行远程命令；仅在 owner-supervised unrestricted 模式下真实执行。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.ssh.execute',
    capability: 'ssh.exec',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['ssh', 'remote', 'server', '远程执行'],
    rollback: { strategy: 'caller_defined', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.ssh.inventory',
    name: 'SSH 配置清单',
    description: '只读解析本机 SSH config 的 Host 元数据；不读取私钥、不连接远端、不触发密码提示。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.ssh.inventory',
    capability: 'ssh.inventory',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['ssh', 'inventory', 'config', '远程执行'],
    rollback: { strategy: 'none_readonly' },
  },
  {
    id: 'noe.freedom.keychain.read',
    name: 'Keychain 密钥代理',
    description: '读取 macOS Keychain 中指定 account/service 的存在性和内部 secretRef；不把密钥值输出到 API、日志或 ledger。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.keychain.read',
    capability: 'secret.keychain',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['keychain', 'secret', 'api-key', '钥匙串'],
    rollback: { strategy: 'none_readonly' },
  },
  {
    id: 'noe.freedom.env.inspect',
    name: '.env 脱敏检查',
    description: '读取指定 .env 文件的键名和脱敏值预览；不输出原始 secret。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.env.inspect',
    capability: 'secret.env',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['env', 'secret', 'dotenv', '环境变量'],
    rollback: { strategy: 'none_readonly' },
  },
  {
    id: 'noe.freedom.desktop.inventory',
    name: '桌面清单',
    description: '列出桌面或指定目录的文件名、类型和大小；不读取文件内容。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.desktop.inventory',
    capability: 'desktop.inventory',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['desktop', 'inventory', 'files', '桌面清单'],
    rollback: { strategy: 'none_readonly' },
  },
  {
    id: 'noe.freedom.account.connection_inventory',
    name: '账号平台连接清单',
    description: '汇总 Neo 可操作的社交平台入口、当前浏览器 URL/title 匹配、动作链和回滚要求；不读取 cookie、密码或页面正文。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.account.connection_inventory',
    capability: 'account.connection_inventory',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['account', 'inventory', 'browser', 'social', '账号控制'],
    rollback: { strategy: 'none_readonly' },
  },
  {
    id: 'noe.freedom.developer.readiness_audit',
    name: '开发者模式可控能力盘点',
    description: '实机盘点浏览器登录态、社交平台入口、SSH 清单、工具市场、桌面清单、Keychain secretRef 和模型 provider 凭证可用性元数据；可选联网 health probe；不读取 cookie、密码、页面正文或密钥明文。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.developer.readiness_audit',
    capability: 'developer.readiness_audit',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['developer-mode', 'readiness', 'account', 'browser', 'ssh', 'keychain', 'tool-marketplace', '能力盘点'],
    rollback: { strategy: 'none_readonly' },
  },
  {
    id: 'noe.freedom.social.publish',
    name: '社交平台发布',
    description: '向配置的 webhook / 平台适配器发布内容；真实发布必须 owner-supervised 并保留 evidence。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.publish',
    capability: 'social.publish',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'publish', 'post', '社交发布'],
    rollback: { strategy: 'platform_delete_or_correction', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.social.workflow.prepare',
    name: '社交发布流程准备',
    description: '为抖音、小红书、B 站等平台生成发布前流程、浏览器动作、草稿和回滚计划；不直接按下最终发布。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.workflow.prepare',
    capability: 'social.workflow.prepare',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'workflow', 'publish', 'draft', 'browser', '社交发布'],
    rollback: { strategy: 'cancel_draft_or_platform_correction' },
  },
  {
    id: 'noe.freedom.social.publish_orchestrate',
    name: '社交发布总控编排',
    description: '把账号清单、草稿、预检、填表、上传、最终发布和发布后探测串成可审计动作链；开发者真实执行可串联上传、最终发布和回滚动作，具体副作用仍由子动作授权与 evidence 记录。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.publish_orchestrate',
    capability: 'social.publish_orchestrate',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'workflow', 'orchestrate', 'publish', 'account', '社交发布'],
    rollback: { strategy: 'cancel_local_draft_before_external_publish' },
  },
  {
    id: 'noe.freedom.chain.execute',
    name: 'Freedom 动作链执行',
    description: '按顺序执行 Noe Freedom 动作链；每个子动作仍走原授权、硬红线、脱敏、evidence 和可选 ledger，不直接绕过底层工具边界。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.chain.execute',
    capability: 'workflow.chain.execute',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['workflow', 'chain', 'batch', 'developer-mode', '自由执行'],
    rollback: { strategy: 'per_step_rollback', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.run.resume_next_actions',
    name: 'Freedom Ledger 续跑下一步',
    description: '从已保存的 Freedom run ledger 校验并恢复 runtime.nextFreedomActions，再交给动作链连续执行；用于刷新页面或隔天继续长任务。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.run.resume_next_actions',
    capability: 'workflow.resume.next_actions',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['workflow', 'resume', 'ledger', 'chain', '自由执行'],
    rollback: { strategy: 'per_step_rollback', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.run.history',
    name: 'Freedom Run 历史清单',
    description: '只读列出最近 Freedom run ledger 摘要，标出可续跑的 nextFreedomActions，并生成续跑动作；不执行历史动作。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.run.history',
    capability: 'workflow.run_history',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['workflow', 'ledger', 'history', 'resume', '自由执行'],
    rollback: { strategy: 'none_readonly' },
  },
  {
    id: 'noe.freedom.social.preflight.run',
    name: '社交发布前实机检查',
    description: '检查本地发布草稿、媒体文件元数据和浏览器平台页状态，产出下一步可执行动作；不读取媒体内容，不最终发布。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.preflight.run',
    capability: 'social.preflight',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'preflight', 'publish', 'media', 'browser', '社交发布'],
    rollback: { strategy: 'none_preflight_only' },
  },
  {
    id: 'noe.freedom.social.form_fill.plan',
    name: '社交表单填充计划',
    description: '基于本地草稿生成平台专用 JXA/DOM 填表脚本；脚本只填标题/正文，不处理媒体上传，不点击最终发布。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.form_fill.plan',
    capability: 'social.form_fill.plan',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'form-fill', 'publish', 'browser', 'automation', '社交发布'],
    rollback: { strategy: 'clear_form_or_reload_page' },
  },
  {
    id: 'noe.freedom.social.form_fill.execute',
    name: '社交表单受控填充',
    description: '执行 Noe 生成的受控 JXA 填表脚本，只填标题/正文；执行前拒绝 click/submit/final publish 动作。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.form_fill.execute',
    capability: 'social.form_fill.execute',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'form-fill', 'publish', 'browser', 'automation', 'execute', '社交发布'],
    rollback: { strategy: 'clear_form_or_reload_page', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.social.media_upload.prepare',
    name: '社交媒体上传准备',
    description: '检查本地媒体文件元数据并生成上传控件选择器探测脚本；不读取媒体内容，不选择文件，不开始上传，不最终发布。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.media_upload.prepare',
    capability: 'social.media_upload.prepare',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'media', 'upload', 'selector', 'browser', '社交发布'],
    rollback: { strategy: 'none_prepare_only' },
  },
  {
    id: 'noe.freedom.social.media_upload.execute',
    name: '社交媒体受控上传',
    description: '执行 Noe 生成的受控 JXA 上传脚本，只选择一个本地媒体文件并启动平台上传队列；不点击最终发布。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.media_upload.execute',
    capability: 'social.media_upload.execute',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'media', 'upload', 'browser', 'automation', 'execute', '社交发布'],
    rollback: { strategy: 'cancel_draft_or_remove_uploaded_media', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.social.final_publish.execute',
    name: '社交最终发布',
    description: '执行 Noe 生成的受控 JXA 最终发布点击脚本，并记录发布后 URL/title 与回滚证据；不读取 cookie、密码或页面正文。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.final_publish.execute',
    capability: 'social.final_publish.execute',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'publish', 'final', 'browser', 'automation', 'execute', '社交发布'],
    rollback: { strategy: 'platform_delete_hide_or_correction', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.social.rollback.evidence_gate',
    name: '社交回滚证据门控',
    description: '为已发布帖子的删除/隐藏/撤回/修正生成可审计的证据门控：仅评估目标 URL、发布后证据、操作前证据与可信破坏性授权，并产出下一步真实回滚动作。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.rollback.evidence_gate',
    capability: 'social.rollback.evidence_gate',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'rollback', 'delete', 'hide', 'evidence', 'gate', '回滚'],
    rollback: { strategy: 'none_gate_only_no_real_action' },
  },
  {
    id: 'noe.freedom.social.rollback.execute',
    name: '社交真实回滚执行',
    description: '在 developer_unrestricted / owner 授权下，通过本机浏览器登录态执行已发布内容的删除、隐藏、撤回或修正点击；不读取 cookie、密码或页面正文。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.rollback.execute',
    capability: 'social.rollback.execute',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'rollback', 'delete', 'hide', 'recall', 'browser', 'automation', 'execute', '真实删除'],
    rollback: { strategy: 'platform_state_probe_or_manual_recreate', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.browser.open',
    name: '浏览器打开链接',
    description: '用本机默认浏览器打开指定 URL，可利用当前浏览器登录态进入账号页面；不读取 cookie 或密码。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.browser.open',
    capability: 'browser.open',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['browser', 'account', 'open-url', '账号控制'],
    rollback: { strategy: 'close_tab_or_window' },
  },
  {
    id: 'noe.freedom.browser.state_probe',
    name: '浏览器账号状态探测',
    description: '通过 macOS 脚本读取前台 App 和可脚本化浏览器的当前 URL/title/window 元数据；不读取 cookie、密码或页面内容。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.browser.state_probe',
    capability: 'browser.state.probe',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['browser', 'account', 'state-probe', 'url', '账号控制'],
    rollback: { strategy: 'none_readonly' },
  },
  {
    id: 'noe.freedom.browser.dom.execute',
    name: '浏览器 DOM 动作执行',
    description: '对当前浏览器标签执行受控 DOM 动作 DSL（读标题、聚焦、填值、点击）；用于控制已登录账号页面，不读取 cookie、密码或页面正文，动作值不写入 ledger。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.browser.dom.execute',
    capability: 'browser.dom.execute',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['browser', 'dom', 'account', 'automation', 'execute', '账号控制'],
    rollback: { strategy: 'caller_defined_or_page_reload', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.macos.applescript.run',
    name: 'macOS 自动化脚本',
    description: '运行 AppleScript 或 JXA 控制本机 App、浏览器和系统 UI；开发者模式可直接执行。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.macos.applescript.run',
    capability: 'automation.applescript',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['macos', 'applescript', 'jxa', 'browser', 'desktop-automation', '账号控制'],
    rollback: { strategy: 'caller_defined', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.social.draft.create',
    name: '社交发布草稿',
    description: '创建本地社交发布草稿和回滚计划；不调用外部平台，不产生发布副作用。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.draft.create',
    capability: 'social.draft.create',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'draft', 'publish', '社交发布'],
    rollback: { strategy: 'cancel_draft' },
  },
  {
    id: 'noe.freedom.social.draft.list',
    name: '社交草稿清单',
    description: '列出本地社交发布草稿元数据；不读取密钥，不调用外部平台。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.draft.list',
    capability: 'social.draft.list',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'draft', 'list', '社交发布'],
    rollback: { strategy: 'none_readonly' },
  },
  {
    id: 'noe.freedom.social.draft.cancel',
    name: '取消社交草稿',
    description: '取消本地社交发布草稿；不删除外部内容，不调用外部平台。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.social.draft.cancel',
    capability: 'social.draft.cancel',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['social', 'draft', 'cancel', '社交发布'],
    rollback: { strategy: 'recreate_draft' },
  },
  {
    id: 'noe.freedom.file.delete',
    name: '本地文件删除',
    description: '把 owner 指定的本地文件或目录移入 macOS 废纸篓；拒绝系统根目录、用户主目录、Noe/Codex 密钥配置目录等硬红线目标。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.file.delete',
    capability: 'file.delete',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['file', 'delete', 'trash', 'filesystem', '自由执行'],
    rollback: { strategy: 'macos_trash_put_back', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.network.upload',
    name: '外部上传',
    description: '上传文本或文件引用到外部 HTTP endpoint；真实上传必须 owner-supervised。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.network.upload',
    capability: 'network.upload',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['upload', 'http', 'external', '上传'],
    rollback: { strategy: 'endpoint_defined', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.tool_marketplace.install',
    name: '工具市场安装',
    description: '安装经过 trust manifest 描述的本地工具；真实安装写入用户级 Noe marketplace 目录。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.tool_marketplace.install',
    capability: 'tool.install',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['tool-marketplace', 'install', 'skill', '工具市场'],
    rollback: { strategy: 'remove_installed_manifest', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.tool_marketplace.list',
    name: '工具市场清单',
    description: '列出 Noe 工具市场中已登记工具的元数据；不执行工具代码。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.tool_marketplace.list',
    capability: 'tool.registry.list',
    risk_level: 'high',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['tool-marketplace', 'list', 'registry', '工具市场'],
    rollback: { strategy: 'none_readonly' },
  },
  {
    id: 'noe.freedom.tool_marketplace.disable',
    name: '工具市场禁用',
    description: '禁用已登记工具并写入 tombstone；不删除原始外部资源，不执行工具代码。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.tool_marketplace.disable',
    capability: 'tool.registry.disable',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['tool-marketplace', 'disable', 'registry', '工具市场'],
    rollback: { strategy: 'reinstall_manifest', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.tool_marketplace.uninstall',
    name: '工具市场卸载',
    description: '卸载工具市场登记记录并保留 disabled tombstone；不执行工具代码。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.tool_marketplace.uninstall',
    capability: 'tool.registry.uninstall',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['tool-marketplace', 'uninstall', 'registry', '工具市场'],
    rollback: { strategy: 'reinstall_manifest', requiredForRealExecute: true },
  },
  {
    id: 'noe.freedom.tool_marketplace.execute',
    name: '工具市场执行',
    description: '执行已安装工具的声明入口；必须经过 trust manifest、allowlist 和 evidence 记录。',
    version: '1.0.0',
    category: 'freedom',
    operation: 'noe.freedom.tool_marketplace.execute',
    capability: 'tool.execute',
    risk_level: 'critical',
    dryRunSupported: true,
    permissionRequired: true,
    tags: ['tool-marketplace', 'execute', 'skill', '工具执行'],
    rollback: { strategy: 'tool_defined', requiredForRealExecute: true },
  },
];

export const BUILTIN_FREEDOM_QUICK_STARTS = [
  {
    id: 'developer.shell.safe-echo',
    title: 'Shell 自检',
    description: '用开发者模式跑一个无害 echo，验证真实执行链、ledger 和脱敏是否可用。',
    actionId: 'noe.freedom.shell.execute',
    mode: 'developer_unrestricted',
    args: { command: 'printf noe-developer-mode' },
    tags: ['shell', 'developer-mode', 'smoke'],
  },
  {
    id: 'desktop.inventory',
    title: '桌面清单',
    description: '列出桌面文件名、类型和大小，不读取文件内容。',
    actionId: 'noe.freedom.desktop.inventory',
    mode: 'developer_unrestricted',
    args: { dirPath: '~/Desktop', maxEntries: 60 },
    tags: ['desktop', 'inventory'],
  },
  {
    id: 'file.delete.placeholder',
    title: '本地文件移入废纸篓',
    description: '把指定本地文件或目录移入 macOS 废纸篓；请先替换 path。',
    actionId: 'noe.freedom.file.delete',
    mode: 'developer_unrestricted',
    args: { path: '~/Desktop/替换为要移入废纸篓的文件' },
    tags: ['file', 'delete', 'trash'],
  },
  {
    id: 'ssh.inventory',
    title: 'SSH Host 清单',
    description: '只读解析 SSH config 元数据，不读私钥、不连接远端。',
    actionId: 'noe.freedom.ssh.inventory',
    mode: 'developer_unrestricted',
    args: {},
    tags: ['ssh', 'inventory'],
  },
  {
    id: 'account.connection-inventory.social',
    title: '账号平台连接清单',
    description: '列出抖音、小红书、B 站、视频号、YouTube 的创作者入口、浏览器匹配状态、可执行动作链和回滚要求。',
    actionId: 'noe.freedom.account.connection_inventory',
    mode: 'developer_unrestricted',
    args: { platforms: ['douyin', 'xiaohongshu', 'bilibili', 'wechat_channels', 'youtube'], browserState: {} },
    tags: ['account', 'inventory', 'social'],
  },
  {
    id: 'developer.readiness-audit',
    title: '开发者模式能力盘点',
    description: '实机检查浏览器登录态、账号平台入口、SSH、工具市场、桌面清单、Keychain secretRef 和模型 provider 凭证可用性，可选联网 health probe，产出下一步动作。',
    actionId: 'noe.freedom.developer.readiness_audit',
    mode: 'developer_unrestricted',
    args: {
      platforms: ['douyin', 'xiaohongshu', 'bilibili', 'wechat_channels', 'youtube'],
      includeBrowserState: true,
      includeSshInventory: true,
      includeMarketplace: true,
      includeDesktop: true,
      includeProviderSecrets: true,
      includeProviderHealth: false,
      providerSecrets: ['minimax', 'xiaomi', 'gemini', 'openai', 'anthropic'],
      keychainRefs: [],
    },
    tags: ['developer-mode', 'readiness', 'account'],
  },
  {
    id: 'browser.open-douyin-creator',
    title: '打开抖音创作者中心',
    description: '用默认浏览器打开账号页面，利用现有登录态；不读 cookie 或密码。',
    actionId: 'noe.freedom.browser.open',
    mode: 'developer_unrestricted',
    args: { url: 'https://creator.douyin.com/' },
    tags: ['browser', 'social', 'douyin'],
  },
  {
    id: 'social.workflow.douyin',
    title: '抖音发布流程准备',
    description: '生成抖音创作者中心发布前流程、草稿和回滚计划；不会直接发布。',
    actionId: 'noe.freedom.social.workflow.prepare',
    mode: 'developer_unrestricted',
    args: { platform: 'douyin', title: '待替换标题', content: '请替换成要发布的内容', mediaFiles: [] },
    tags: ['social', 'workflow', 'douyin'],
  },
  {
    id: 'social.orchestrate.douyin',
    title: '抖音发布总控编排',
    description: '生成从账号检查、草稿、预检、填表、上传到最终发布和回滚探测的完整动作链；不会自动最终发布。',
    actionId: 'noe.freedom.social.publish_orchestrate',
    mode: 'developer_unrestricted',
    args: { platform: 'douyin', title: '待替换标题', content: '请替换成要发布的内容', mediaFiles: [], browserState: {}, browserApp: 'Google Chrome' },
    tags: ['social', 'workflow', 'orchestrate', 'douyin'],
  },
  {
    id: 'social.dom-publish-actions.douyin',
    title: '抖音 DOM 发布动作包',
    description: '生成抖音 DOM 填标题/正文、媒体控件和最终发布点击动作；默认只载入参数，执行时仍写 ledger 和脱敏 evidence。',
    actionId: 'noe.freedom.social.publish_orchestrate',
    mode: 'developer_unrestricted',
    args: {
      platform: 'douyin',
      title: '待替换标题',
      content: '请替换成要发布的内容',
      mediaFiles: ['替换为本地视频路径'],
      browserState: {},
      browserApp: 'Google Chrome',
      includeDomMediaPickerAction: true,
      includeDomFinalPublishAction: true,
    },
    tags: ['social', 'dom', 'publish', 'execute', 'douyin'],
  },
  {
    id: 'freedom.chain.echo-and-inventory',
    title: '动作链自检',
    description: '连续 dry-run/执行两个无害 Freedom 步骤，验证动作链编排、逐步授权和 ledger。',
    actionId: 'noe.freedom.chain.execute',
    mode: 'developer_unrestricted',
    args: {
      stopOnError: true,
      steps: [
        { stepId: 'shell_echo', actionId: 'noe.freedom.shell.execute', args: { command: 'printf noe-chain-ok' } },
        { stepId: 'desktop_inventory', actionId: 'noe.freedom.desktop.inventory', args: { dirPath: '~/Desktop', maxEntries: 10 } },
      ],
    },
    tags: ['workflow', 'chain', 'smoke'],
  },
  {
    id: 'freedom.resume-next-actions.placeholder',
    title: '从 ledger 续跑下一步',
    description: '读取已保存 Freedom run ledger 的 nextFreedomActions，并载入/执行为动作链；请替换 ledgerRef。',
    actionId: 'noe.freedom.run.resume_next_actions',
    mode: 'developer_unrestricted',
    args: {
      ledgerRef: 'output/noe-freedom-runs/替换为runId/ledger.json',
      stopOnError: true,
      persistChildLedgers: true,
    },
    tags: ['workflow', 'resume', 'ledger'],
  },
  {
    id: 'freedom.run-history.recent',
    title: '最近 Freedom run 清单',
    description: '列出最近 Freedom run ledger，自动标出可续跑项并生成续跑动作。',
    actionId: 'noe.freedom.run.history',
    mode: 'developer_unrestricted',
    args: { limit: 20, requireOk: true, onlyWithNextActions: false },
    tags: ['workflow', 'history', 'resume', 'ledger'],
  },
  {
    id: 'social.preflight.douyin',
    title: '抖音发布前检查',
    description: '检查草稿、媒体文件和浏览器是否在抖音创作者中心；不会最终发布。',
    actionId: 'noe.freedom.social.preflight.run',
    mode: 'developer_unrestricted',
    args: { platform: 'douyin', draftId: '替换为草稿ID', mediaFiles: [], browserState: {} },
    tags: ['social', 'preflight', 'douyin'],
  },
  {
    id: 'social.form-fill.douyin',
    title: '抖音表单填充计划',
    description: '从本地草稿生成抖音标题/正文填表脚本；不上传媒体，不点击发布。',
    actionId: 'noe.freedom.social.form_fill.plan',
    mode: 'developer_unrestricted',
    args: { platform: 'douyin', draftId: '替换为草稿ID', browserState: {}, browserApp: 'Google Chrome' },
    tags: ['social', 'form-fill', 'douyin'],
  },
  {
    id: 'social.form-fill-execute.douyin',
    title: '抖音受控填表',
    description: '执行受控填表脚本，只填标题/正文；不点击发布。',
    actionId: 'noe.freedom.social.form_fill.execute',
    mode: 'developer_unrestricted',
    args: { platform: 'douyin', draftId: '替换为草稿ID', browserState: {}, browserApp: 'Google Chrome' },
    tags: ['social', 'form-fill', 'execute', 'douyin'],
  },
  {
    id: 'social.media-upload.douyin',
    title: '抖音媒体上传准备',
    description: '检查本地媒体并生成抖音上传控件选择器探测脚本；不选择文件、不点击上传。',
    actionId: 'noe.freedom.social.media_upload.prepare',
    mode: 'developer_unrestricted',
    args: { platform: 'douyin', draftId: '替换为草稿ID', mediaFiles: [], browserState: {}, browserApp: 'Google Chrome' },
    tags: ['social', 'media', 'upload', 'douyin'],
  },
  {
    id: 'social.media-upload-execute.douyin',
    title: '抖音媒体受控上传',
    description: '选择一个本地媒体文件并启动抖音上传队列；不点击最终发布。',
    actionId: 'noe.freedom.social.media_upload.execute',
    mode: 'developer_unrestricted',
    args: { platform: 'douyin', draftId: '替换为草稿ID', mediaFiles: [], browserState: {}, browserApp: 'Google Chrome' },
    tags: ['social', 'media', 'upload', 'execute', 'douyin'],
  },
  {
    id: 'social.final-publish.douyin',
    title: '抖音最终发布',
    description: '点击抖音发布按钮并记录发布后 URL/title 与回滚证据；不读取 cookie、密码或页面正文。',
    actionId: 'noe.freedom.social.final_publish.execute',
    mode: 'developer_unrestricted',
    args: { platform: 'douyin', draftId: '替换为草稿ID', browserState: {}, browserApp: 'Google Chrome' },
    tags: ['social', 'publish', 'final', 'execute', 'douyin'],
  },
  {
    id: 'social.rollback-execute.douyin',
    title: '抖音真实回滚',
    description: '在已打开或可打开的发布内容页面执行删除/隐藏/撤回点击；请先替换 targetPostUrl 并提供发布后证据。',
    actionId: 'noe.freedom.social.rollback.execute',
    mode: 'developer_unrestricted',
    args: {
      platform: 'douyin',
      rollbackAction: 'delete',
      targetPostUrl: 'https://www.douyin.com/video/替换为作品ID',
      browserApp: 'Google Chrome',
      clickConfirm: true,
      postPublishEvidence: { url: 'https://www.douyin.com/video/替换为作品ID', title: '替换为已发布标题' },
      beforeActionEvidence: { capturedBy: 'noe.freedom.browser.state_probe', domDigest: '替换为操作前证据' },
    },
    tags: ['social', 'rollback', 'delete', 'execute', 'douyin'],
  },
  {
    id: 'browser.open-xiaohongshu-creator',
    title: '打开小红书创作服务',
    description: '用默认浏览器打开账号页面，后续可接 macOS 自动化完成发布流程。',
    actionId: 'noe.freedom.browser.open',
    mode: 'developer_unrestricted',
    args: { url: 'https://creator.xiaohongshu.com/' },
    tags: ['browser', 'social', 'xiaohongshu'],
  },
  {
    id: 'social.workflow.xiaohongshu',
    title: '小红书发布流程准备',
    description: '生成小红书发布前流程、草稿和回滚计划；不会直接发布。',
    actionId: 'noe.freedom.social.workflow.prepare',
    mode: 'developer_unrestricted',
    args: { platform: 'xiaohongshu', title: '待替换标题', content: '请替换成要发布的内容', mediaFiles: [] },
    tags: ['social', 'workflow', 'xiaohongshu'],
  },
  {
    id: 'social.preflight.xiaohongshu',
    title: '小红书发布前检查',
    description: '检查草稿、媒体文件和浏览器是否在小红书创作服务；不会最终发布。',
    actionId: 'noe.freedom.social.preflight.run',
    mode: 'developer_unrestricted',
    args: { platform: 'xiaohongshu', draftId: '替换为草稿ID', mediaFiles: [], browserState: {} },
    tags: ['social', 'preflight', 'xiaohongshu'],
  },
  {
    id: 'social.form-fill.xiaohongshu',
    title: '小红书表单填充计划',
    description: '从本地草稿生成小红书标题/正文填表脚本；不上传媒体，不点击发布。',
    actionId: 'noe.freedom.social.form_fill.plan',
    mode: 'developer_unrestricted',
    args: { platform: 'xiaohongshu', draftId: '替换为草稿ID', browserState: {}, browserApp: 'Google Chrome' },
    tags: ['social', 'form-fill', 'xiaohongshu'],
  },
  {
    id: 'social.form-fill-execute.xiaohongshu',
    title: '小红书受控填表',
    description: '执行受控填表脚本，只填标题/正文；不点击发布。',
    actionId: 'noe.freedom.social.form_fill.execute',
    mode: 'developer_unrestricted',
    args: { platform: 'xiaohongshu', draftId: '替换为草稿ID', browserState: {}, browserApp: 'Google Chrome' },
    tags: ['social', 'form-fill', 'execute', 'xiaohongshu'],
  },
  {
    id: 'social.media-upload.xiaohongshu',
    title: '小红书媒体上传准备',
    description: '检查本地媒体并生成小红书上传控件选择器探测脚本；不选择文件、不点击上传。',
    actionId: 'noe.freedom.social.media_upload.prepare',
    mode: 'developer_unrestricted',
    args: { platform: 'xiaohongshu', draftId: '替换为草稿ID', mediaFiles: [], browserState: {}, browserApp: 'Google Chrome' },
    tags: ['social', 'media', 'upload', 'xiaohongshu'],
  },
  {
    id: 'social.media-upload-execute.xiaohongshu',
    title: '小红书媒体受控上传',
    description: '选择一个本地媒体文件并启动小红书上传队列；不点击最终发布。',
    actionId: 'noe.freedom.social.media_upload.execute',
    mode: 'developer_unrestricted',
    args: { platform: 'xiaohongshu', draftId: '替换为草稿ID', mediaFiles: [], browserState: {}, browserApp: 'Google Chrome' },
    tags: ['social', 'media', 'upload', 'execute', 'xiaohongshu'],
  },
  {
    id: 'social.final-publish.xiaohongshu',
    title: '小红书最终发布',
    description: '点击小红书发布按钮并记录发布后 URL/title 与回滚证据；不读取 cookie、密码或页面正文。',
    actionId: 'noe.freedom.social.final_publish.execute',
    mode: 'developer_unrestricted',
    args: { platform: 'xiaohongshu', draftId: '替换为草稿ID', browserState: {}, browserApp: 'Google Chrome' },
    tags: ['social', 'publish', 'final', 'execute', 'xiaohongshu'],
  },
  {
    id: 'social.workflow.bilibili',
    title: 'B 站发布流程准备',
    description: '生成 B 站视频发布前流程、草稿和回滚计划；不会直接发布。',
    actionId: 'noe.freedom.social.workflow.prepare',
    mode: 'developer_unrestricted',
    args: { platform: 'bilibili', title: '待替换标题', content: '请替换成要发布的内容', mediaFiles: [] },
    tags: ['social', 'workflow', 'bilibili'],
  },
  {
    id: 'macos.jxa.front-browser-url',
    title: '读取前台浏览器 URL',
    description: '用 JXA 读取前台 Chrome/Safari 标签 URL，作为账号自动化前的状态探测。',
    actionId: 'noe.freedom.browser.state_probe',
    mode: 'developer_unrestricted',
    args: { includeAll: true },
    tags: ['macos', 'jxa', 'browser'],
  },
  {
    id: 'browser.dom.read-title',
    title: '浏览器 DOM 动作自检',
    description: '在当前浏览器标签执行只读标题/URL 探测，验证通用账号页面 DOM 动作通道。',
    actionId: 'noe.freedom.browser.dom.execute',
    mode: 'developer_unrestricted',
    args: { browserApp: 'Google Chrome', actions: [{ type: 'read_title' }] },
    tags: ['browser', 'dom', 'account', 'smoke'],
  },
  {
    id: 'upload.file.placeholder',
    title: '文件上传模板',
    description: '把本地文件引用上传到 HTTP endpoint；请先替换 url 和 filePath。',
    actionId: 'noe.freedom.network.upload',
    mode: 'developer_unrestricted',
    args: { url: 'https://example.test/upload', method: 'POST', filePath: 'README.md' },
    tags: ['upload', 'file', 'http'],
  },
  {
    id: 'tool-marketplace.list',
    title: '工具市场清单',
    description: '列出已安装工具市场记录，不执行工具代码。',
    actionId: 'noe.freedom.tool_marketplace.list',
    mode: 'developer_unrestricted',
    args: {},
    tags: ['tool-marketplace', 'inventory'],
  },
];

function clean(value, max = 2000) {
  return redactSensitiveText(String(value ?? '').trim()).slice(0, max);
}

function safeJson(value) {
  if (!value || typeof value !== 'object') return {};
  try {
    return JSON.parse(redactSensitiveText(JSON.stringify(value)));
  } catch {
    return {};
  }
}

export function normalizeNoeFreedomTool(input = {}) {
  const id = clean(input.id || input.operation, 180);
  if (!id) return null;
  return {
    schemaVersion: NOE_FREEDOM_MANIFEST_SCHEMA_VERSION,
    id,
    name: clean(input.name || input.title || id, 180),
    description: clean(input.description || '', 1200),
    version: clean(input.version || '1.0.0', 40),
    category: clean(input.category || 'freedom', 80),
    operation: clean(input.operation || id, 180),
    capability: clean(input.capability || input.operation || id, 120),
    riskLevel: clean(input.riskLevel || input.risk_level || 'critical', 40).toLowerCase(),
    dryRunSupported: input.dryRunSupported !== false,
    permissionRequired: input.permissionRequired !== false,
    tags: [...new Set([...(Array.isArray(input.tags) ? input.tags : []), ...(Array.isArray(input.capabilityTags) ? input.capabilityTags : [])].map((tag) => clean(tag, 80)).filter(Boolean))],
    rollback: safeJson(input.rollback),
    trust: {
      source: clean(input.trust?.source || input.source || 'builtin', 80),
      allowlistRequired: input.trust?.allowlistRequired !== false,
      evidenceRequired: input.trust?.evidenceRequired !== false,
      secretOutputDenied: input.trust?.secretOutputDenied !== false,
    },
  };
}

export function listNoeFreedomTools({ includeHidden = true } = {}) {
  const tools = BUILTIN_FREEDOM_TOOLS.map(normalizeNoeFreedomTool).filter(Boolean);
  return includeHidden ? tools : tools.filter((tool) => tool.riskLevel !== 'critical');
}

export function normalizeNoeFreedomQuickStart(input = {}) {
  const id = clean(input.id, 160);
  const actionId = clean(input.actionId || input.action || input.toolId, 180);
  if (!id || !actionId) return null;
  return {
    id,
    title: clean(input.title || id, 160),
    description: clean(input.description || '', 800),
    actionId,
    mode: NOE_FREEDOM_AUTH_MODES.has(clean(input.mode, 80)) ? clean(input.mode, 80) : 'developer_unrestricted',
    args: safeJson(input.args),
    tags: [...new Set((Array.isArray(input.tags) ? input.tags : []).map((tag) => clean(tag, 80)).filter(Boolean))],
  };
}

export function listNoeFreedomQuickStarts() {
  return BUILTIN_FREEDOM_QUICK_STARTS.map(normalizeNoeFreedomQuickStart).filter((item) => item && findNoeFreedomTool(item.actionId));
}

export function findNoeFreedomTool(id = '') {
  const target = clean(id, 180).toLowerCase();
  return listNoeFreedomTools().find((tool) => tool.id.toLowerCase() === target || tool.operation.toLowerCase() === target) || null;
}

export function freedomToolsAsCommandManifests() {
  return BUILTIN_FREEDOM_TOOLS.map((tool) => ({
    id: tool.id,
    name: tool.name,
    title: tool.name,
    description: tool.description,
    version: tool.version,
    category: tool.category,
    risk_level: tool.risk_level,
    riskLevel: tool.risk_level,
    operation: tool.operation,
    dryRunSupported: tool.dryRunSupported,
    permissionRequired: true,
    tags: tool.tags,
    capabilityTags: tool.tags,
    source: 'freedom-builtin',
    inputSchema: {
      type: 'object',
      properties: {
        args: { type: 'object', description: '工具参数；secret 字段会脱敏' },
        authorization: {
          type: 'object',
          description: '真实执行需 owner-supervised 或 developer_unrestricted 授权；secret 字段会脱敏',
        },
        realExecute: { type: 'boolean', description: 'true 才真实执行；默认 dry-run' },
      },
    },
  }));
}

export function validateNoeFreedomAuthorization({
  tool = null,
  authorization = {},
  realExecute = false,
} = {}) {
  const errors = [];
  const mode = clean(authorization.mode || (realExecute ? '' : 'dry_run'), 80);
  if (!NOE_FREEDOM_AUTH_MODES.has(mode)) errors.push('invalid_freedom_authorization_mode');
  const developerMode = mode === 'developer_unrestricted';
  if (realExecute && !['owner_supervised_unrestricted', 'developer_unrestricted'].includes(mode)) {
    errors.push('owner_supervised_unrestricted_required_for_real_execute');
  }
  if (realExecute && authorization.ownerPresent !== true) errors.push('owner_present_required_for_real_execute');
  if (realExecute && authorization.systemOverride === true) errors.push('system_level_override_denied');
  if (tool?.trust?.allowlistRequired && realExecute && !developerMode && authorization.allowlistAccepted !== true) errors.push('allowlist_acceptance_required');
  if (tool?.rollback?.requiredForRealExecute && realExecute && !developerMode && !clean(authorization.rollbackPlan || authorization.rollbackRef, 1000)) {
    errors.push('rollback_plan_required');
  }
  return {
    ok: errors.length === 0,
    errors,
    mode,
    ownerPresent: authorization.ownerPresent === true,
    realExecute: realExecute === true,
  };
}

function redactUrlLikeText(value = '') {
  const text = clean(value, 2000);
  if (!text) return '';
  try {
    const url = new URL(text);
    for (const key of [...url.searchParams.keys()]) {
      if (/token|key|secret|password|code|auth|session|credential|jwt/i.test(key)) {
        url.searchParams.set(key, '[redacted]');
      }
    }
    if (/token|key|secret|password|auth|session|credential|jwt/i.test(url.hash)) {
      url.hash = '#[redacted]';
    }
    return clean(url.toString(), 2000);
  } catch {
    return text.replace(/([?&#][^=]*?(?:token|key|secret|password|code|auth|session|credential|jwt)[^=]*=)[^&#\s]+/gi, '$1[redacted]');
  }
}

export function redactNoeFreedomPayload(value) {
  if (typeof value === 'string') return redactUrlLikeText(value);
  if (typeof value === 'number' || typeof value === 'boolean' || value == null) return value;
  if (Array.isArray(value)) return value.slice(0, 50).map(redactNoeFreedomPayload);
  if (!value || typeof value !== 'object') return clean(value, 400);
  const looksLikeBrowserDomAction = Boolean(value.selector || value.type || value.kind || value.action);
  const out = {};
  for (const [key, item] of Object.entries(value).slice(0, 80)) {
    const k = clean(key, 120);
    const sensitiveKey = /secret|token|key|password|authorization|credential|cookie/i.test(k);
    const browserDomValueKey = looksLikeBrowserDomAction && /^(value|text|content)$/i.test(k);
    out[k] = sensitiveKey && !(typeof item === 'number' || typeof item === 'boolean' || item == null)
      ? '[redacted]'
      : browserDomValueKey && !(typeof item === 'number' || typeof item === 'boolean' || item == null)
      ? '[redacted]'
      : redactNoeFreedomPayload(item);
  }
  return out;
}
