import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const mindHtml = readFileSync(join(root, 'public/mind.html'), 'utf8');
const mindJs = readFileSync(join(root, 'public/mind.js'), 'utf8');
const mindCss = readFileSync(join(root, 'public/mind.css'), 'utf8');
const earthJs = readFileSync(join(root, 'public/src/web/noe-world-earth.js'), 'utf8');
const failureModesJs = readFileSync(join(root, 'public/mind-failure-modes.js'), 'utf8');

describe('Noe mind world surface UI', () => {
  it('mounts a real world-surface panel on the mind dashboard', () => {
    expect(mindHtml).toContain('id="worldSurface"');
    expect(mindHtml).toContain('id="worldEarthCanvas"');
    expect(mindHtml).toContain('id="worldEarthStatus"');
    expect(mindHtml).toContain('id="worldSurfaceSvg"');
    expect(mindHtml).toContain('id="worldHotspots"');
    expect(mindHtml).toContain('id="worldInsight"');
    expect(mindHtml).toContain('id="worldFilters"');
    expect(mindHtml).toContain('id="worldFocusRisk"');
    expect(mindHtml).toContain('id="worldLegend"');
    expect(mindHtml).toContain('id="worldChinaView"');
    expect(mindHtml).toContain('id="worldLocateMe"');
    expect(mindHtml).toContain('id="worldEarthView"');
    expect(mindHtml).toContain('id="worldChinaPanel"');
    expect(mindHtml).not.toContain('data-world-bg-mode');
    expect(mindHtml).toContain('id="opsSummary"');
    expect(mindHtml).toContain('ops-command-deck');
    expect(mindHtml).toContain('id="actionNotice"');
    expect(mindHtml).toContain('id="workMapFilters"');
    expect(mindHtml.indexOf('id="worldSurface"')).toBeLessThan(mindHtml.indexOf('id="statusStrip"'));
    expect(mindHtml).toContain('诺伊 · 运行中枢');
    expect(mindHtml).toContain('实时态势地球');
    expect(mindHtml).toContain('右侧选择态势');
    expect(mindHtml).toContain('中国视图');
    expect(mindHtml).toContain('定位我');
    expect(mindHtml).not.toContain('静空');
    expect(mindHtml).not.toContain('深空');
    expect(mindHtml).not.toContain('星云');
    expect(mindHtml).toContain('态势控制栏');
    expect(mindHtml).toContain('点选右侧条目查看证据与动作');
    expect(mindHtml).toContain('id="memoryDetails"');
    expect(mindHtml).toContain('id="workMapDetails"');
    expect(mindHtml).toContain('id="opsLogDetails"');
    expect(mindHtml).toContain('id="panelLogSummaryRail"');
    expect(mindHtml).toContain('id="panelLogRefreshBtn"');
    expect(mindHtml).toContain('id="panelLogLines"');
    expect(mindHtml).toContain('id="brainDetails"');
    expect(mindHtml).not.toContain('NOE LIVE EARTH');
    expect(mindHtml).not.toContain('Noe100 Proof');
    expect(mindHtml).not.toContain('Mission Runtime');
    expect(mindHtml).not.toContain('地球外侧光点');
    expect(mindHtml).not.toContain('点击热点');
  });

  it('renders BaiLongma-style earth hotspots from live Noe endpoints instead of decorative static data', () => {
    expect(mindJs).toContain('function renderWorldSurface');
    expect(mindJs).toContain('function renderWorldSurfaceEarth');
    expect(mindJs).toContain('function buildWorldHotspots');
    expect(mindJs).toContain('function socialCredentialStats');
    expect(mindJs).toContain('function socialCredentialLabel');
    expect(mindJs).toContain('function socialAdmissionStats');
    expect(mindJs).toContain('function socialAdmissionSummary');
    expect(mindJs).toContain('function socialAdmissionReasonCn');
    expect(mindJs).toMatch(/import\('\.\/src\/web\/noe-world-earth\.js\?v=[^']+'\)/);
    expect(mindJs).toContain('WORLD_HOTSPOT_LAYOUT');
    expect(mindJs).toContain("placement: 'orbit'");
    expect(mindJs).not.toContain('lat: 31.2');
    expect(mindJs).toContain("worldApi('/api/noe/readiness')");
    expect(mindJs).toContain("worldApi('/api/noe/social-inbound/status')");
    expect(mindJs).toContain("worldApi('/api/noe/boot-self-check/status')");
    expect(mindJs).toContain('bootSelfCheck.status');
    expect(mindJs).toContain('bootSelfCheck.counts');
    expect(mindJs).toContain('panel_runtime_preflight');
    expect(mindJs).toContain('bootSelfCheck.checks.panel_runtime_preflight.detail');
    expect(mindJs).toContain('companion_tools_preflight');
    expect(mindJs).toContain('bootSelfCheck.checks.companion_tools_preflight.detail');
    expect(mindJs).toContain('function bootCompanionToolsText');
    expect(mindJs).toContain('开爪');
    expect(mindJs).toContain('赫尔墨斯');
    expect(mindJs).toContain('readiness.credentialSummary');
    expect(mindJs).toContain('readiness.credentialStatuses');
    expect(mindJs).toContain('receiver.turnGuard');
    expect(mindJs).toContain('wechatPersonal.receiver.turnGuard');
    expect(mindJs).toContain('qq.receiver.turnGuard');
    expect(mindJs).toContain('入站接纳');
    expect(mindJs).toContain('入站拦截');
    expect(mindJs).toContain('personalContract');
    expect(mindJs).toContain('qqDryRunReady');
    expect(mindJs).toContain("worldApi('/api/noe/missions?limit=10')");
    expect(mindJs).toContain("worldApi('/api/noe/mind/proof')");
    expect(mindJs).toContain("worldApi('/api/noe/mind/vitals')");
    expect(mindJs).toContain("worldApi('/api/noe/mind/overview')");
    expect(mindJs).not.toMatch(/Math\.random|sampleHotspot|demoHotspot/);
  });

  it('turns the earth into an evidence-backed operations surface instead of passive ornament', () => {
    expect(mindJs).toContain('WORLD_FILTERS');
    expect(mindJs).toContain('function renderWorldFilters');
    expect(mindJs).toContain('function chooseWorldDefaultHotspot');
    expect(mindJs).toContain('function renderWorldInsight');
    expect(mindJs).toContain('function worldDiagnosticText');
    expect(mindJs).toContain('function setChinaPanel');
    expect(mindJs).toContain('function locateWorldUser');
    expect(mindJs).toContain('function updateChinaLocation');
    expect(mindJs).not.toContain('function setWorldBackgroundMode');
    expect(mindJs).toContain('function showActionNotice');
    expect(mindJs).not.toContain('alert(');
    expect(mindJs).toContain('function bootPanelRuntimeText');
    expect(mindJs).toContain('function openContainingDetails');
    expect(mindJs).toContain("history.scrollRestoration = 'manual'");
    expect(mindJs).toContain('51835 属于本仓库');
    expect(mindJs).toContain('data-world-filter');
    expect(mindJs).toContain('data-world-action="jump"');
    expect(mindJs).toContain('data-world-action="refresh"');
    expect(mindJs).toContain('data-world-action="social-checklist"');
    expect(mindJs).toContain('data-world-action="qq-preview"');
    expect(mindJs).toContain('扣扣预演');
    expect(mindJs).toContain('data-world-action="wechat-contract"');
    expect(mindJs).toContain('data-world-action="boot-run"');
    expect(mindJs).toContain('data-world-action="boot-repair"');
    expect(mindJs).toContain('data-world-action="copy"');
    expect(mindJs).toContain("apiOutcome('/api/noe/boot-self-check/run'");
    expect(mindJs).toContain("apiOutcome('/api/noe/boot-self-check/repair'");
    expect(mindJs).toContain("apiOutcome('/api/noe/social-inbound/qq/preview'");
    expect(mindJs).toContain("apiOutcome('/api/noe/social-inbound/wechat-personal/outbound-dry-run'");
    expect(mindJs).toContain('function renderPanelLogTail');
    expect(mindJs).toContain('function loadPanelLogTail');
    expect(mindJs).toContain("api('/api/noe/panel-log-tail?limit=80&maxBytes=32768')");
    expect(mindJs).toContain('opsLogDetails');
    expect(mindJs).toContain('panelLogRefreshBtn');
    expect(mindJs).toContain('sourcePaths');
    expect(mindJs).toContain('nextAction');
    expect(mindJs).toContain('targetSelector');
    expect(mindJs).not.toContain('world-route');
    expect(mindJs).not.toContain('_addRoutes');
  });

  it('keeps the panel visually bounded and responsive', () => {
    expect(mindCss).toContain('.world-surface');
    expect(mindCss).toContain('.world-body');
    expect(mindCss).toContain('.detail-accordion');
    expect(mindCss).toContain('.detail-section');
    expect(mindCss).toContain('.panel-log');
    expect(mindCss).toContain('.panel-log-lines');
    expect(mindCss).toContain('.panel-log-line');
    expect(mindCss).toContain('.ops-summary');
    expect(mindCss).toContain("--ops-ui-texture: url('/vendor/ui/noe_ops_control_surface_gpt_20260614.png')");
    expect(mindCss).toContain('.ops-summary::before');
    expect(mindCss).toContain('.ops-command-deck');
    expect(mindCss).toContain('.action-notice');
    expect(mindCss).toContain('.world-head-actions');
    expect(mindCss).toContain('.world-filters');
    expect(mindCss).toContain('.world-insight');
    expect(mindCss).toContain('.world-command-row');
    expect(mindCss).toContain('.world-earth-toolbar');
    expect(mindCss).not.toContain('.world-bg-modes');
    expect(mindCss).toContain('.world-china-panel');
    expect(mindCss).toContain('.world-china-map');
    expect(mindCss).toContain('.world-card-meta');
    expect(mindCss).toContain('height: clamp(440px, calc(100svh - 178px), 640px)');
    expect(mindCss).toContain('overflow-y: auto');
    expect(mindCss).toContain('#worldEarthCanvas');
    expect(mindCss).toContain('#worldSurfaceSvg');
    expect(mindCss).toContain('.world-orb.fallback');
    expect(mindCss).toContain('background: #03060a;');
    expect(mindCss).toContain('scroll-margin-top');
    expect(mindCss).toContain('@media (max-width: 760px)');
    expect(mindCss).not.toContain('.world-route');
    expect(mindCss).not.toContain('radial-gradient(ellipse at center, #0a1a2e');
  });

  it('turns status points into reference-style orbiting dots around the earth', () => {
    expect(earthJs).toContain('function orbitToVec3');
    expect(earthJs).toContain('function orbitPoints');
    expect(earthJs).toContain('function applyOrbitPlane');
    expect(earthJs).toContain('function createOrbitNodeTexture');
    expect(earthJs).toContain('function buildOrbitNodeMarker');
    expect(earthJs).toContain('ORBIT_NODE_MOTION_GAIN');
    expect(earthJs).toContain('const elapsed = Math.max(0, now - (this.orbitStartTime || now))');
    expect(earthJs).toContain('elapsed * speed * ORBIT_NODE_MOTION_GAIN');
    expect(earthJs).toContain('orbitNodeRecords');
    expect(earthJs).toContain('orbitPickTargets');
    expect(earthJs).toContain('_buildOrbitNodes');
    expect(earthJs).toContain('_updateOrbitNodePositions');
    expect(earthJs).toContain('leader.geometry.setFromPoints');
    expect(earthJs).not.toContain('function buildSatellite3DModel');
    expect(earthJs).not.toContain('function buildSatelliteSpriteModel');
    expect(earthJs).not.toContain('function satelliteSpriteCell');
    expect(earthJs).not.toContain('function buildSpaceStationModel');
    expect(earthJs).not.toContain('function atlasTextureCell');
    expect(earthJs).not.toContain('/vendor/satellites/');
    expect(earthJs).not.toContain('satelliteMaterialAtlasTex');
    expect(earthJs).not.toContain('satelliteSpriteAtlasTex');
    expect(earthJs).not.toContain('new T.BoxGeometry');
    expect(earthJs).not.toContain('new T.CylinderGeometry');
    expect(earthJs).not.toContain('new T.ConeGeometry');
    expect(earthJs).toContain('/vendor/orbit-nodes/noe_orbit_node_beacons_gpt_20260613.png');
    expect(earthJs).toContain('ORBIT_NODE_ATLAS_CELLS');
    expect(earthJs).toContain('atlasTex?.image');
    expect(earthJs).toContain('new T.CanvasTexture(canvas)');
    expect(earthJs).toContain('new T.SpriteMaterial');
    expect(earthJs).toContain('rings.outerArc.rotation.z');
    expect(earthJs).toContain('rings.innerArc.rotation.z');
    expect(earthJs).toContain('new T.TorusGeometry');
    expect(earthJs).toContain('new T.SphereGeometry(0.014');
    expect(earthJs).toContain('function createLabelTexture');
    expect(earthJs).toContain('function createNightLightsTexture');
    expect(earthJs).toContain('function solarSubpoint');
    expect(earthJs).toContain('function geoToSpherePoint');
    expect(earthJs).toContain('function createEarthDayNightMaterial');
    expect(earthJs).toContain('_isPointOccludedByEarth');
    // 背景由 scene.background 静态接管深空贴图;原 _buildBackgroundLayer 漂移层(永不被调用的死代码)已清理。
    expect(earthJs).toContain('this.scene.background = spaceTex');
    expect(earthJs).toContain('_pickHotspot');
    expect(earthJs).toContain("point.placement !== 'geo'");
    expect(earthJs).toContain('this.scene.add(this.hotspotGroup)');
    expect(earthJs).toContain('this.hotspots.forEach((point, index) =>');
    expect(earthJs).toContain('new T.LineLoop');
    expect(earthJs).toContain('new T.Sprite');
    expect(earthJs).toContain('noe-world-hotspot-select');
    expect(earthJs).toContain('/vendor/space/noe_deep_space_reference_gpt_20260613.png');
    expect(earthJs).not.toContain('/vendor/space/noe_starfield_gpt_20260613.png');
    expect(earthJs).not.toContain('/vendor/space/noe_starfield_dark_gpt_20260613.png');
    expect(earthJs).not.toContain('/vendor/space/noe_starfield_quiet_gpt_20260613.png');
    expect(earthJs).toContain('CHINA_OUTLINE');
    expect(earthJs).toContain('focusChina');
    expect(earthJs).toContain('setUserLocation');
    expect(mindJs).not.toContain('data-world-node');
    expect(earthJs).toContain('createMoonTexture');
    expect(earthJs).toContain('/vendor/moon/moon_albedo_gpt_20260613.png');
    expect(earthJs).not.toContain('createNebulaTexture');
    expect(earthJs).not.toContain('_buildNebula');
    expect(earthJs).toContain('_buildMoon');
    expect(earthJs).toContain('this.moonGroup.rotation.y +=');
    expect(earthJs).toContain('noeMoonRadius');
    expect(earthJs).toContain('_updateMoonOcclusion');
    expect(earthJs).toContain('_isMoonInsideEarthDisc');
    expect(earthJs).toContain('this.moon.visible = true');
    expect(earthJs).toContain('new T.SphereGeometry(moonRadius');
    expect(earthJs).not.toContain('new T.RingGeometry');
    expect(mindJs).toContain('function worldCardActionLabel');
    expect(mindJs).toContain('world-card-led');
    expect(mindJs).toContain('world-card-index');
  });

  it('mounts P7-H1 failure mode attribution as a read-only proof companion', () => {
    expect(mindHtml).toContain('/mind-failure-modes.js?v=earth-clean-20260614b');
    expect(failureModesJs).toContain("api('/api/noe/mind/proof')");
    expect(failureModesJs).toContain('proof.failureModes');
    expect(failureModesJs).toContain('proofFailureModes');
    expect(failureModesJs).toContain('proof-failure-details');
    expect(failureModesJs).toContain('故障归因');
    expect(failureModesJs).toContain('cnCluster');
    expect(failureModesJs).toContain('cnNextAction');
    expect(failureModesJs).toContain('下一步已记录');
    expect(failureModesJs).not.toContain('P7-H0 failure modes');
    expect(failureModesJs).not.toContain('J0-lite ready');
    expect(failureModesJs).not.toContain('/ evidence ');
    expect(failureModesJs).not.toContain("method: 'POST'");
    expect(failureModesJs).not.toContain('method: "POST"');
    expect(mindCss).toContain('.proof-failure-modes');
    expect(mindCss).toContain('.proof-failure-details');
    expect(mindCss).toContain('.failure-mode-row');
  });
});
